SRC = Barbarian.cpp
SRC += BlueMen.cpp
SRC += Creature.cpp
SRC += D6.cpp
SRC += D10.cpp
SRC += D12.cpp
SRC += Die.cpp
SRC += HarryPotter.cpp
SRC += InputValid.cpp
SRC += LineupNode.cpp
SRC += LoserNode.cpp
SRC += main.cpp
SRC += Medusa.cpp
SRC += Menu.cpp
SRC += Vampire.cpp

default: $(SRC)
	g++ -std=c++11  $(SRC) -o main

clean:
	rm main